# Generated by Django 5.1 on 2024-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder',
            field=models.DateTimeField(null=True, verbose_name='Reminding date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatEveryDay',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatEveryWeek',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatOne',
            field=models.BooleanField(null=True),
        ),
    ]
