# Generated by Django 5.1 on 2024-11-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_description_alter_task_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeatEveryDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatEveryWeek',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeatOne',
            field=models.BooleanField(default=False),
        ),
    ]
