# Generated by Django 5.1 on 2024-11-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_mydb_remove_fileattachment_taskid_remove_task_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorohistorydb',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Completed', max_length=10),
        ),
        migrations.AddField(
            model_name='reminderdb',
            name='reminderMode',
            field=models.CharField(choices=[('Before Due Date', 'Before Due Date'), ('At Specific Moment', 'At Specific Moment')], default='Before Due Date', max_length=20),
        ),
        migrations.AddField(
            model_name='todoitemdb',
            name='itemType',
            field=models.CharField(choices=[('Project', 'Project'), ('Section', 'Section'), ('Task', 'Task')], default='Task', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminderdb',
            name='specificTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Specific time'),
        ),
        migrations.AlterField(
            model_name='taskattributesdb',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='todoitemdb',
            name='labelID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.labeldb'),
        ),
        migrations.AlterField(
            model_name='todoitemdb',
            name='parentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.todoitemdb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='avatarURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
