# Generated by Django 5.1 on 2024-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_pomodorohistorydb_status_reminderdb_remindermode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorohistorydb',
            name='currentDuration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Running', 'Running'), ('Paused', 'Paused'), ('Canceled', 'Canceled')], default='Completed', max_length=10),
        ),
    ]
