# Generated by Django 5.1 on 2024-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_pomodorohistorydb_currentduration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationtokendb',
            name='tokenValue',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
