# Generated by Django 5.1 on 2024-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_alter_authenticationtokendb_tokenvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemdb',
            name='itemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
