# Generated by Django 5.1 on 2024-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_todoitemdb_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationtokendb',
            name='tokenID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labeldb',
            name='labelID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logsdb',
            name='logID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediadb',
            name='mediaID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='pomodoroID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reminderdb',
            name='reminderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='websiteblockingdb',
            name='blockID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
