# Generated by Django 5.1 on 2024-12-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_alter_authenticationtokendb_tokenid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorohistorydb',
            name='intervals',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='taskattributesdb',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='taskattributesdb',
            name='inTodayDate',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='In Today date'),
        ),
    ]
