# Generated by Django 5.1 on 2024-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_pomodorohistorydb_intervals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='endTime',
            field=models.DateTimeField(null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='startTime',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
    ]
