# Generated by Django 5.1 on 2024-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_alter_pomodorohistorydb_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='intervals',
            field=models.JSONField(default=list),
        ),
    ]
