# Generated by Django 5.1 on 2024-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_alter_pomodorohistorydb_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
