# Generated by Django 5.1 on 2024-12-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_alter_pomodorohistorydb_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorohistorydb',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Running', 'Running'), ('Paused', 'Paused'), ('Canceled', 'Canceled')], default='Canceled', max_length=10),
        ),
    ]
