# Generated by Django 5.1 on 2024-12-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_alter_taskattributesdb_description_and_more'),
        ('todolist', '0016_alter_pomodorohistorydb_status'),
    ]

    operations = [
    ]
