name: Docker CI

on:
  push:
    branches:
      - main
      - set-up-docker
      - docker/**
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Check folder
      run: pwd

    - name: Check files
      run: ls -ltr

    - name: Build and run Docker Compose
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Lint flake8
      run: docker-compose exec app flake8

    - name: Run tests
      run: docker-compose exec app python manage.py test
